name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang]


    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build libgtest-dev nlohmann-json3-dev
        
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake ninja googletest nlohmann-json
        
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install cmake ninja
        vcpkg install gtest nlohmann-json

    - name: Configure CMake
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
        
    - name: Build
      run: cmake --build build --config Release
      
    - name: Test
      working-directory: build
      run: ctest --output-on-failure --parallel 4

  examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build nlohmann-json3-dev
        
    - name: Configure CMake
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      
    - name: Build examples
      run: cmake --build build --target basic_sequential agent_pattern async_processing batch_processing
      
    - name: Run examples
      working-directory: build/examples
      run: |
        ./basic_sequential
        ./agent_pattern
        ./async_processing
        ./batch_processing